### ISSUE TITLE
MVP Roadmap discussion

### ISSUE THREAD

**Issue by guilhermebr** [stone-co/the-amazing-ledger#30]
- [x] HTTP API
- [x] Save transactions
- [x] gRPC API
- [x] Linter for the system architecture https://github.com/resotto/gochk
- [x] Get information about an account (balance and current version)
- [x] Get the history of an account (operations)
- [ ] Accounting reports
- [x] End2End tests (gRPC)
- [x] Stress tests (gRPC)
- [ ] Load test (gRPC)

**Comment by gmarcial** [comment]
Hi, the roadmap it is updated? Passed on a good time.

With what I could contribute at the moment?

**Comment by alexgarzao** [comment]
Hello @gmarcial .

At this time, there is just one milestone, that needs to be updated: https://github.com/stone-co/the-amazing-ledger/milestone/1

And this roadmap needs to be updated too.

We will do it soon.

About contributions, nice! Please, give us some time to organize tasks, V1 milestone, and so on.

**Comment by gmarcial** [comment]
Hello @alexgarzao.
 
Yes, the milestone https://github.com/stone-co/the-amazing-ledger/milestone/1 is the unique open with the context of the problem detailed, but already is in progress with another contributor, otherwise, I would analyze.
 
The others, Load and Stress tests, would be necessary to discuss, for example how the cases to be simulated, the design, tooling, and around there, but must be in progress internally.
 
Ok, I will wait and follow the actual and future projects.
 
Thanks 🤘
